name: Terraform Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      action:
        description: "Choose action"
        required: true
        default: "apply"
        type: choice
        options:
          - apply
          - destroy

permissions:
  id-token: write
  contents: read

jobs:

  terraform-plan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::949100095236:role/GitHub_IAM_role
          aws-region: us-east-1

      - run: terraform init
      - run: terraform plan

  terraform-apply:
    needs: terraform-plan
    runs-on: ubuntu-latest

    environment:
      name: prod   # 🔥 THIS ENABLES MANUAL APPROVAL

    if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'apply' }}

    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::949100095236:role/GitHub_IAM_role
          aws-region: us-east-1

      - run: terraform init
      - run: terraform apply -auto-approve

  terraform-destroy:
    needs: terraform-plan
    runs-on: ubuntu-latest

    environment:
      name: prod   # 🔥 SAME APPROVAL GATE

    if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'destroy' }}

    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::949100095136:role/GitHub_IAM_role
          aws-region: us-east-1

      - run: terraform init
      - run: terraform destroy -auto-approve